#!/usr/bin/env bash
# arch_graph.sh — measures the real import graph (lakos) of a Flutter/Dart
# package and regenerates the data block of that project's ARCHITECTURE.md
# (between <!-- arch-graph:start --> and <!-- arch-graph:end -->).
#
# Report-only: never fails the build on its own (arch_violations.py's counts
# are for a human/reviewer to act on). Touches ONLY the marked data block —
# never the curated prose, tree, or diagrams around it.
#
# The layering/direction rule is NOT hardcoded here — see arch_violations.py
# and its arch-graph.config.json schema (project-supplied, lives at the
# project root alongside ARCHITECTURE.md).
#
# Usage: arch_graph.sh [project-root]   (defaults to $PWD)
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="${1:-$(pwd)}"
cd "$PROJECT_ROOT"

DOC="ARCHITECTURE.md"
mkdir -p build

echo "Measuring the import graph (lakos)…"
dart run lakos -m lib > build/arch.dot 2>/dev/null || true

# Guard: if lakos failed (empty/edgeless dot), do NOT overwrite the doc with zeros.
if ! grep -q '\->' build/arch.dot 2>/dev/null; then
  echo "lakos produced no graph (build/arch.dot is empty). Run 'dart run lakos -m lib' directly to see the error." >&2
  echo "  arch-graph block in $DOC left untouched." >&2
  exit 1
fi

BODY=$(python3 "$SCRIPT_DIR/arch_violations.py" build/arch.dot "$(date +%Y-%m-%d)")
export BODY

python3 - "$DOC" <<'PY'
import os, re, sys
doc = sys.argv[1]
body = os.environ["BODY"]
txt = open(doc, encoding="utf-8").read()
start = "<!-- arch-graph:start (generated by scripts/arch_graph.sh — do not hand-edit) -->"
end = "<!-- arch-graph:end -->"
block = f"{start}\n{body}\n{end}"
pat = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
if not pat.search(txt):
    print(f"arch-graph markers not found in {doc}")
    sys.exit(1)
open(doc, "w", encoding="utf-8").write(pat.sub(lambda _: block, txt))
print("arch-graph block updated")
PY
