#!/usr/bin/env bash
# desc: Emit agent-kit's portable epistemic tier for a target AI tool (currently: copilot -> AGENTS.md).
# Source of truth stays the wired SKILL.md; this generates a derivative into the CONSUMER's
# repo — nothing is committed back here (no copy, no drift). Structured so per-skill prompt
# files can be added as new emitters without touching the dispatch.
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$REPO_ROOT/plugins/core/skills/using-agent-kit/SKILL.md"

usage() {
  cat <<'EOF'
Usage: emit-port.sh <tool> [--out DIR]

Tools:
  copilot   emit AGENTS.md — read by GitHub Copilot, Cursor, and other AGENTS.md-honoring tools

Options:
  --out DIR   write output into DIR (default: current directory)
  -h, --help  show this help

Source of truth: plugins/core/skills/using-agent-kit/SKILL.md.
Re-run to refresh; never hand-edit the generated output.
EOF
}

tool=""
out_dir="."
while [ $# -gt 0 ]; do
  case "$1" in
    copilot)    tool="$1" ;;
    --out)      shift; out_dir="${1:-}" ;;
    -h|--help)  usage; exit 0 ;;
    *)          echo "ERROR: unrecognized argument '$1'" >&2; usage >&2; exit 1 ;;
  esac
  shift
done

if [ -z "$tool" ]; then
  echo "ERROR: no target tool given" >&2
  usage >&2
  exit 1
fi
if [ ! -f "$SRC" ]; then
  echo "ERROR: source of truth not found: $SRC" >&2
  exit 1
fi
if [ ! -d "$out_dir" ]; then
  echo "ERROR: --out dir does not exist: $out_dir" >&2
  exit 1
fi

emit_copilot() {
  local dest="$out_dir/AGENTS.md"
  {
    cat <<'HEADER'
<!--
  Generated by agent-kit: scripts/emit-port.sh copilot
  Source of truth: plugins/core/skills/using-agent-kit/SKILL.md
  Do NOT edit AGENTS.md by hand — re-run the emitter to refresh.
-->

# agent-kit — portable epistemic tier

These are agent-kit's epistemic and discipline rules, emitted for AGENTS.md-honoring tools
(GitHub Copilot, Cursor, and others that read `AGENTS.md`). They apply to any project,
regardless of stack or domain.

> **Portability note — enforcement does not travel.** In Claude Code, agent-kit backs these
> rules with deterministic hooks (session-start injection, provenance/citation gates, the
> mobile smell-checker) and with skills that consult a stronger advisor model or dispatch
> blind subagents (grill-me, pipeline, the council postures). None of that machinery runs
> here: under an AGENTS.md-only tool these rules are **advisory** — you are asked to follow
> them, not blocked from violating them — and the advisor/subagent skills degrade to doing
> the equivalent work **inline**. Treat the 🔴-marked rules as hard requirements anyway.

HEADER
    awk '/^## Kit Governance/{exit} /^## Research Depth/{p=1} p' "$SRC"
  } > "$dest"
  echo "Wrote $dest ($(wc -l < "$dest" | tr -d ' ') lines)"
}

case "$tool" in
  copilot) emit_copilot ;;
esac
