#!/usr/bin/env python3
# desc: Generates a deterministic INVENTORY.md at the repo root from the plugins' manifests.
"""generate_inventory.py — generates INVENTORY.md at the repo root from:
  - plugins/*/skills/*/SKILL.md   (frontmatter: name, description, disable-model-invocation)
  - plugins/*/agents/*.md         (frontmatter: name, description)
  - plugins/*/hooks/hooks.json    (event, matcher, script) + the script's `# desc:` line
  - plugins/*/scripts/*           (file name) + the script's `# desc:` line
  - plugins/mobile/.mcp.json      (server name + command)

Pure stdlib (no PyYAML) — frontmatter parsing is manual and restricted to
`key: single-line-value` lines; any unexpected YAML structure (multiline, indentation,
duplicate key) fails the script loud (exit != 0), never silently.

Determinism: every directory enumeration uses sorted(); no timestamp/date enters
the output; paths are repo-relative; writes always use '\n' and utf-8 encoding. This
guarantees byte-identical output across runs for the same file tree.

Usage:
  python3 scripts/generate_inventory.py            # writes INVENTORY.md
  python3 scripts/generate_inventory.py --check    # compares against disk; exit 0 if
                                                     # identical, exit 1 (with a short diff)
                                                     # if divergent or missing.
"""

import datetime
import difflib
import json
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLUGINS = ["core", "council", "team", "mobile"]
INVENTORY_PATH = os.path.join(REPO_ROOT, "INVENTORY.md")

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/generate_inventory.py — do not hand-edit. "
    "Regenerate: python3 scripts/generate_inventory.py -->"
)

FRONTMATTER_KEY_RE = re.compile(r"^([A-Za-z0-9_-]+):\s?(.*)$")
COMMAND_PATH_RE = re.compile(r"\$\{CLAUDE_PLUGIN_ROOT\}/(.+)$")
DESC_LINE_RE = re.compile(r"^#\s*desc:\s*(.+)$")

GOVERNANCE_PATH = os.path.join(REPO_ROOT, "docs", "GOVERNANCE.md")
PROVISIONAL_LINE_RE = re.compile(r"^- `([^`]+)` — valid until (\d{4}-\d{2}-\d{2})$")


def collect_provisional():
    """relative path -> deadline, from the '### Active provisionals' section of docs/GOVERNANCE.md."""
    if not os.path.isfile(GOVERNANCE_PATH):
        return {}
    result = {}
    in_section = False
    with open(GOVERNANCE_PATH, encoding="utf-8") as f:
        for raw in f:
            line = raw.rstrip("\n")
            if line.startswith("### Active provisionals"):
                in_section = True
                continue
            if in_section and (line.startswith("## ") or line.startswith("### ")):
                break
            if in_section:
                m = PROVISIONAL_LINE_RE.match(line)
                if m:
                    if m.group(1) in result:
                        raise InventoryError(
                            f"docs/GOVERNANCE.md: duplicate provisional '{m.group(1)}'"
                        )
                    try:
                        datetime.date.fromisoformat(m.group(2))
                    except ValueError:
                        raise InventoryError(
                            f"docs/GOVERNANCE.md: invalid provisional date: {m.group(2)}"
                        ) from None
                    result[m.group(1)] = m.group(2)
                elif line.startswith("- `"):
                    raise InventoryError(
                        f"docs/GOVERNANCE.md: malformed provisional line: {line}"
                    )
    return result


CONTRACT_PATH = os.path.join(REPO_ROOT, "docs", "GOVERNANCE.md")
CONFORMITY_LINE_RE = re.compile(r"^- `(plugins/[^`]+)` — ([a-zA-Zà-ú-]+)$")


def collect_conformity():
    """SKILL.md path -> skeleton, from the '### Conformity' section of docs/GOVERNANCE.md."""
    if not os.path.isfile(CONTRACT_PATH):
        return {}
    result = {}
    in_section = False
    with open(CONTRACT_PATH, encoding="utf-8") as f:
        for raw in f:
            line = raw.rstrip("\n")
            if line.startswith("### Conformity"):
                in_section = True
                continue
            if in_section and (line.startswith("## ") or line.startswith("### ")):
                break
            if in_section:
                m = CONFORMITY_LINE_RE.match(line)
                if m:
                    result[m.group(1)] = m.group(2)
    return result


class InventoryError(Exception):
    """Raised on any structural problem in a source file — always fatal, never silent."""


def rel(path):
    return os.path.relpath(path, REPO_ROOT).replace(os.sep, "/")


def esc(cell):
    """Escape a markdown table cell: '|' -> '\\|', newline -> space."""
    if cell is None:
        cell = ""
    return cell.replace("\n", " ").replace("|", "\\|")


def parse_frontmatter(path):
    """Restricted manual parse of a `---`-delimited frontmatter block.

    Only accepts top-level, single-line `key: value` entries. Any indented line,
    any line that doesn't match `key: value`, or any duplicate key is treated as
    unexpected YAML structure and raises InventoryError.
    """
    with open(path, encoding="utf-8") as f:
        text = f.read()
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        raise InventoryError(f"{rel(path)}: frontmatter must start with '---' on the first line")
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        raise InventoryError(f"{rel(path)}: frontmatter missing closing '---'")

    result = {}
    for lineno, raw in enumerate(lines[1:end], start=2):
        if not raw.strip():
            continue
        if raw[0] in (" ", "\t"):
            raise InventoryError(
                f"{rel(path)}:{lineno}: indented frontmatter line — multiline value or "
                f"unexpected YAML structure not supported by the manual parser: {raw!r}"
            )
        m = FRONTMATTER_KEY_RE.match(raw)
        if not m:
            raise InventoryError(
                f"{rel(path)}:{lineno}: frontmatter line is not 'key: value': {raw!r}"
            )
        key, val = m.group(1), m.group(2).strip()
        if key in result:
            raise InventoryError(f"{rel(path)}:{lineno}: duplicate frontmatter key '{key}'")
        result[key] = val
    return result


def get_desc_line(script_path):
    """Read the mandatory `# desc: ...` header, which must be line 2 of the file."""
    with open(script_path, encoding="utf-8") as f:
        lines = f.readlines()
    if len(lines) < 2:
        raise InventoryError(f"{rel(script_path)}: file has no line 2 (expected '# desc: ...')")
    line2 = lines[1].rstrip("\n")
    m = DESC_LINE_RE.match(line2.strip())
    if not m:
        raise InventoryError(
            f"{rel(script_path)}: line 2 is not '# desc: ...' — found: {line2!r}"
        )
    return m.group(1).strip()


def collect_skills(plugin, provisional):
    skills_dir = os.path.join(REPO_ROOT, "plugins", plugin, "skills")
    result = []
    if not os.path.isdir(skills_dir):
        return result
    for name in sorted(os.listdir(skills_dir)):
        skill_md = os.path.join(skills_dir, name, "SKILL.md")
        if not os.path.isfile(skill_md):
            continue
        fm = parse_frontmatter(skill_md)
        if "name" not in fm:
            raise InventoryError(f"{rel(skill_md)}: frontmatter missing 'name'")
        if "description" not in fm:
            raise InventoryError(f"{rel(skill_md)}: frontmatter missing 'description'")
        if fm["name"] != name:
            raise InventoryError(
                f"{rel(skill_md)}: frontmatter name '{fm['name']}' differs from directory '{name}'"
            )
        slash_only = fm.get("disable-model-invocation", "").strip().lower() == "true"
        key = f"plugins/{plugin}/skills/{name}"
        deadline = provisional.pop(key, None)
        result.append(
            {
                "name": fm["name"],
                "description": fm["description"],
                "slash_only": slash_only,
                "provisional_until": deadline,
            }
        )
    return result


def collect_agents(plugin, provisional):
    agents_dir = os.path.join(REPO_ROOT, "plugins", plugin, "agents")
    result = []
    if not os.path.isdir(agents_dir):
        return result
    for fname in sorted(os.listdir(agents_dir)):
        if not fname.endswith(".md"):
            continue
        agent_md = os.path.join(agents_dir, fname)
        fm = parse_frontmatter(agent_md)
        if "name" not in fm:
            raise InventoryError(f"{rel(agent_md)}: frontmatter missing 'name'")
        if "description" not in fm:
            raise InventoryError(f"{rel(agent_md)}: frontmatter missing 'description'")
        key = f"plugins/{plugin}/agents/{fname}"
        deadline = provisional.pop(key, None)
        result.append(
            {
                "name": fm["name"],
                "description": fm["description"],
                "provisional_until": deadline,
            }
        )
    return result


def resolve_hook_script_path(plugin, command):
    """Extract the on-disk script path referenced by a hooks.json command string."""
    stripped = command.strip()
    if stripped.startswith('"') and stripped.endswith('"'):
        stripped = stripped[1:-1]
    m = COMMAND_PATH_RE.search(stripped)
    if not m:
        raise InventoryError(
            f"plugins/{plugin}/hooks/hooks.json: command doesn't follow the pattern "
            f'"${{CLAUDE_PLUGIN_ROOT}}/...": {command!r}'
        )
    return os.path.join(REPO_ROOT, "plugins", plugin, m.group(1))


def collect_hooks(plugin):
    hooks_json = os.path.join(REPO_ROOT, "plugins", plugin, "hooks", "hooks.json")
    result = []
    if not os.path.isfile(hooks_json):
        return result
    with open(hooks_json, encoding="utf-8") as f:
        data = json.load(f)
    for event, entries in data.get("hooks", {}).items():
        for entry in entries:
            matcher = entry.get("matcher", "")
            for hook in entry.get("hooks", []):
                command = hook.get("command", "")
                script_path = resolve_hook_script_path(plugin, command)
                if not os.path.isfile(script_path):
                    raise InventoryError(
                        f"plugins/{plugin}/hooks/hooks.json: referenced script does not exist: "
                        f"{rel(script_path)}"
                    )
                desc = get_desc_line(script_path)
                result.append(
                    {
                        "hook": os.path.basename(script_path),
                        "event": event,
                        "matcher": matcher,
                        "description": desc,
                    }
                )
    return result


def collect_scripts(plugin):
    scripts_dir = os.path.join(REPO_ROOT, "plugins", plugin, "scripts")
    result = []
    if not os.path.isdir(scripts_dir):
        return result
    for name in sorted(os.listdir(scripts_dir)):
        script_path = os.path.join(scripts_dir, name)
        if not os.path.isfile(script_path):
            continue
        desc = get_desc_line(script_path)
        result.append({"name": name, "description": desc})
    return result


def collect_mcp(plugin):
    mcp_path = os.path.join(REPO_ROOT, "plugins", plugin, ".mcp.json")
    result = []
    if not os.path.isfile(mcp_path):
        return result
    with open(mcp_path, encoding="utf-8") as f:
        data = json.load(f)
    servers = data.get("mcpServers", {})
    for name in sorted(servers.keys()):
        server = servers[name]
        result.append({"name": name, "command": server.get("command", "")})
    return result


def render_table(headers, rows):
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    for row in rows:
        lines.append("| " + " | ".join(esc(c) for c in row) + " |")
    return lines


def render_plugin_section(plugin, provisional, conformity):
    lines = [f"## Plugin `{plugin}`", ""]

    skills = collect_skills(plugin, provisional)
    lines.append(f"### Skills ({len(skills)})")
    lines.append("")
    rows = []
    for s in skills:
        if s["slash_only"]:
            name_cell = f"`{s['name']}` (slash-only: `/{plugin}:{s['name']}`)"
        else:
            name_cell = f"`{s['name']}`"
        if s.get("provisional_until"):
            name_cell += f" ⏳ provisional until {s['provisional_until']}"
        contract = conformity.get(f"plugins/{plugin}/skills/{s['name']}/SKILL.md", "pending")
        rows.append([name_cell, contract, s["description"]])
    lines.extend(render_table(["Skill", "Contract (D14)", "Description"], rows))
    desc_total = sum(len(s["description"].encode("utf-8")) for s in skills)
    lines.append("")
    lines.append(f"Description aggregate (D16): {desc_total} bytes.")
    lines.append("")

    agents = collect_agents(plugin, provisional)
    lines.append(f"### Agents ({len(agents)})")
    lines.append("")
    rows = []
    for a in agents:
        name_cell = f"`{a['name']}`"
        if a.get("provisional_until"):
            name_cell += f" ⏳ provisional until {a['provisional_until']}"
        rows.append([name_cell, a["description"]])
    lines.extend(render_table(["Agent", "Description"], rows))
    lines.append("")

    hooks = collect_hooks(plugin)
    lines.append(f"### Hooks ({len(hooks)})")
    lines.append("")
    rows = [[f"`{h['hook']}`", h["event"], h["matcher"], h["description"]] for h in hooks]
    lines.extend(render_table(["Hook", "Event", "Matcher", "Description"], rows))
    lines.append("")

    scripts = collect_scripts(plugin)
    lines.append(f"### Scripts ({len(scripts)})")
    lines.append("")
    rows = [[f"`{s['name']}`", s["description"]] for s in scripts]
    lines.extend(render_table(["Script", "Description"], rows))
    lines.append("")

    if plugin == "mobile":
        mcp = collect_mcp(plugin)
        lines.append(f"### MCP ({len(mcp)})")
        lines.append("")
        rows = [[f"`{m['name']}`", f"`{m['command']}`"] for m in mcp]
        lines.extend(render_table(["Server", "Command"], rows))
        lines.append("")

    return lines


def generate():
    lines = [
        GENERATED_BANNER,
        "# agent-kit inventory",
        "",
        "Generated automatically from the plugins' manifests (`SKILL.md`, agents, "
        "`hooks.json`, scripts, and `.mcp.json`) — do not hand-edit; regenerate with "
        "`python3 scripts/generate_inventory.py`.",
        "",
        "Skills marked **slash-only** have `disable-model-invocation: true` in their "
        "frontmatter: they run only via an explicit command (`/<plugin>:<name>`), never on "
        "the model's own initiative (criterion: `docs/GOVERNANCE.md` §SKILL.md contract).",
        "",
        "Items with “provisional until <date>” are wired under the deadline exception "
        "(`docs/GOVERNANCE.md` §Active provisionals) — a missed deadline turns the gate red.",
        "",
        "---",
        "",
    ]
    provisional = collect_provisional()
    conformity = collect_conformity()
    for i, plugin in enumerate(PLUGINS):
        lines.extend(render_plugin_section(plugin, provisional, conformity))
        if i < len(PLUGINS) - 1:
            lines.append("---")
            lines.append("")
    if provisional:
        raise InventoryError(
            "provisionals in docs/GOVERNANCE.md without a matching artifact: "
            + ", ".join(sorted(provisional))
        )
    # single trailing newline
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def main():
    check_mode = "--check" in sys.argv[1:]
    try:
        content = generate()
    except InventoryError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    if check_mode:
        if not os.path.isfile(INVENTORY_PATH):
            print("ERROR: INVENTORY.md does not exist — run without --check to generate it.", file=sys.stderr)
            return 1
        with open(INVENTORY_PATH, encoding="utf-8") as f:
            disk_content = f.read()
        if disk_content == content:
            print("OK: INVENTORY.md is up to date.")
            return 0
        diff = difflib.unified_diff(
            disk_content.splitlines(keepends=True),
            content.splitlines(keepends=True),
            fromfile="INVENTORY.md (disk)",
            tofile="INVENTORY.md (generated)",
        )
        diff_text = "".join(diff)
        max_chars = 4000
        if len(diff_text) > max_chars:
            diff_text = diff_text[:max_chars] + "\n... (diff truncated)"
        print("FAILED: INVENTORY.md is out of date.\n", file=sys.stderr)
        print(diff_text, file=sys.stderr)
        return 1

    with open(INVENTORY_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print(f"OK: {rel(INVENTORY_PATH)} generated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
